pipeline {
    agent any

    tools {
        maven 'Maven 3'
        jdk 'JDK 21'
    }

    environment {
        SONARQUBE = 'MySonar'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/gopalraj321/my-java-project.git'
            }
        }

        stage('Build') {
            steps {
                dir('my-java-app') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('my-java-app') {
                    withSonarQubeEnv('MySonar') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('my-java-app/target') {
                    // Assuming your artifact is my-java-app.jar; change if needed
                    sh 'cp my-java-app.jar /home/gopalraj321/'
                }
                echo 'Artifact copied to /home/gopalraj321/'
            }
        }
    }
}
