pipeline {
    agent any

    tools {
        maven 'Maven 3'
        jdk 'JDK 21'
    }

    environment {
        SONARQUBE = 'MySonar'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/gopalraj321/my-java-project.git'
            }
        }

        stage('Build') {
            steps {
                dir('my-java-app') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('my-java-app') {
                    withSonarQubeEnv('MySonar') {
                        bat 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('my-java-app/target') {
                    bat 'copy my-java-app-1.0.0.jar C:\\Users\\Gopal\\Desktop\\Gopal Cloud Documents'
                }
                echo 'Artifact copied to C:\\Users\\Gopal\\Desktop\\Gopal Cloud Documents'
            }
        }
    }
}
